### PR TITLE
Fix - Timeout error in build

### LINKED ISSUE #211: Intermittent Timeout in build
There is a problem in our build downloading the Digicert CA

```
  [2023-02-06T14:37:32.573Z] AxiosError: connect ETIMEDOUT 91.199.212.73:443
      at Function.AxiosError.from (file:///workspaces/ccf-app-samples/data-reconciliation-app/node_modules/axios/lib/core/AxiosError.js:89:14)
      at RedirectableRequest.handleRequestError (file:///workspaces/ccf-app-samples/data-reconciliation-app/node_modules/axios/lib/adapters/http.js:569:25)
      at RedirectableRequest.emit (node:events:513:28)
      at RedirectableRequest.emit (node:domain:489:12)
      at ClientRequest.eventHandlers.<computed> (/workspaces/ccf-app-samples/data-reconciliation-app/node_modules/follow-redirects/index.js:14:24)
      at ClientRequest.emit (node:events:513:28)
      at ClientRequest.emit (node:domain:489:12)
      at TLSSocket.socketErrorListener (node:_http_client:481:9)
      at TLSSocket.emit (node:events:513:28)
      at TLSSocket.emit (node:domain:489:12) {
    port: 443,
    address: '91.199.212.73',
    syscall: 'connect',
    code: 'ETIMEDOUT',
    errno: -110,
    config: {
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false
      },
      adapter: [ 'xhr', 'http' ],
      transformRequest: [ [Function: transformRequest] ],
      transformResponse: [ [Function: transformResponse] ],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: [TLSSocket],
        _header: 'GET /?d=853428 HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'User-Agent: axios/1.3.2\r\n' +
          'Accept-Encoding: gzip, compress, deflate, br\r\n' +
          'Host: crt.sh\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: [Agent],
        socketPath: undefined,
        method: 'GET',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        path: '/?d=853428',
        _ended: false,
        res: null,
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'crt.sh',
        protocol: 'https:',
        _redirectable: [Circular *1],
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype],
        [Symbol(kUniqueHeaders)]: null
      },
      _currentUrl: 'https://crt.sh/?d=853428',
      [Symbol(kCapture)]: false
    },
    cause: Error: connect ETIMEDOUT 91.199.212.73:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '91.199.212.73',
      port: 443
    }
  }
```

### PR DESCRIPTION
**Pull request by kusweta**
Fix #211 

I have added a default timeout of 1 min.
Have tested it several times and it's not giving error.

### CODE REVIEW

File: data-reconciliation-app/test/utils/jwt-config-generator.ts [hunk 1]
```diff
@@ -3,29 +3,29 @@ import * as fs from "fs";
...
-
     const proposalFilePath = `${this.workspaceFolderPath}/set_jwt_issuer_test_proposal.json`;
     const sandboxConfigFilePath = `${this.workspaceFolderPath}/set_jwt_issuer_test_sandbox.json`;
-    if (fs.existsSync(sandboxConfigFilePath) && fs.existsSync(proposalFilePath)) 
+    if (fs.existsSync(sandboxConfigFilePath) && fs.existsSync(proposalFilePath))
       return;
 
     // make sure the workspace folder exists.
-    await fs.promises.mkdir(this.workspaceFolderPath, { recursive: true }).catch(console.error);
+    await fs.promises
```
Comment (macromania) [inline data-reconciliation-app/test/utils/jwt-config-generator.ts:26]: Your prettier settings printWidth might be set to 80 which makes reading this code a bit hard 🥲.

Would you mind either reversing these formatting changes or setting your prettier to 240 and reformat it so it could look like before 😅?

Comment (kusweta) [reply data-reconciliation-app/test/utils/jwt-config-generator.ts]: Thanks for pointing it out. I've changed it to 240 :)

**Review by ross-p-smith — APPROVED** [review]
Let's watch the build and check that this doesn't come back. Good use of keep alive instance.
